services:
  astro-app:
    build: .
    volumes:
      - .:/app:rw
    ports:
      - "4321:4321"
    stdin_open: true
    tty: true
    networks:
      - suffgo-network

networks:
  suffgo-network:
    external: true  # Indica que es una red externa
